owner: caro-health
repo: upptime

sites:
  - name: Caro Company Site
    url: https://caro.health
  - name: Caro Blog
    url: https://blog.caro.health
  - name: Caro API Server
    url: https://vjtbsbd4htmgs3z6qtxpmy72z40ddkae.lambda-url.eu-west-1.on.aws/api/status

status-website:
  # cname: status.caro.health
  baseUrl: /upptime
  logoUrl: https://assets-global.website-files.com/608bf6784677334250865824/608bf6c642c663f3ccaf0dbe_webclip.png
  name: Caro Health Status
  introTitle: "**Caro Health Status**"
  introMessage: This is the status page for [Caro Health](https://caro.health) services. We are continuously monitoring our services for you. If you encounter any issues, please [let us know](mailto:support@caro.health).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 */3 * * *"

# See https://upptime.js.org/docs/configuration
