owner: caro-health
repo: upptime

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: Caro Company Site
    url: https://caro.health

status-website:
  # cname: status.caro.health
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Caro Health Status
  introTitle: "**Caro Health Status**"
  introMessage: This is the status page for [Caro Health](https://caro.health) services. We are continuously monitoring our services for you. If you encounter any issues, please [let us know](mailto:support@caro.health).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "0 */3 * * *"

# See https://upptime.js.org/docs/configuration
